version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    env_file:
      - .env.production
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  image_worker:
    build: .
    container_name: rq_image_worker
    command: rq worker --url redis://redis-server:6379 image_generation
    env_file:
      - .env.production
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  video_worker:
    build: .
    container_name: rq_video_worker
    command: rq worker --url redis://redis-server:6379 video_generation
    env_file:
      - .env.production
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  upscale_worker:
    build: .
    container_name: rq_upscale_worker
    command: rq worker --url redis://redis-server:6379 upscale
    env_file:
      - .env.production
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  rq_dashboard:
    image: eoranged/rq-dashboard
    container_name: rq_dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis-server:6379
    ports:
      - "9181:9181"
    depends_on:
      - redis
    restart: unless-stopped
